/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 할 일 목록 조회 */
        get: operations["TaskController_findAll"];
        put?: never;
        /** 할 일 생성 */
        post: operations["TaskController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 할 일 상세 조회 */
        get: operations["TaskController_getDetail"];
        /** 할 일 수정 */
        put: operations["TaskController_updateContent"];
        post?: never;
        /** 할 일 삭제 */
        delete: operations["TaskController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 할 일 완료 */
        put: operations["TaskController_complete"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/cancel-complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 할 일 완료 취소 */
        put: operations["TaskController_cancelComplete"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 스케줄 목록 조회 */
        get: operations["ScheduleController_findAll"];
        put?: never;
        /** 스케줄 등록 */
        post: operations["ScheduleController_createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 할 일 상세 조회 */
        get: operations["ScheduleController_getDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 스케줄 내용 수정 */
        put: operations["ScheduleController_updateSchedule"];
        post?: never;
        /** 스케줄 삭제) */
        delete: operations["ScheduleController_moveToTodoList"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{scheduleId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 스케줄 완료 */
        put: operations["ScheduleController_completeSchedule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{scheduleId}/cancel-complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 스케줄 완료 취소 */
        put: operations["ScheduleController_cancelComplete"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{scheduleId}/move-to-todo-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 스케줄 할일 목록으로 이동) */
        put: operations["ScheduleController_moveToScheduleList"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TaskItemResponse: {
            /**
             * @description 할 일 ID
             * @example 1
             */
            taskId: number;
            /**
             * @description 할 일 이름
             * @example 프로젝트 회의
             */
            name: string;
            /**
             * @description 완료 여부
             * @example false
             */
            isCompleted: boolean;
        };
        TaskListResponse: {
            /** @description 할 일 목록 */
            tasks: components["schemas"]["TaskItemResponse"][];
        };
        TaskCreateRequest: {
            /** @description 할일 이름 */
            name: string;
        };
        TaskCreateResponseData: {
            /**
             * @description 생성된 할일 ID
             * @example 1
             */
            taskId: number;
        };
        TaskCreateResponse: {
            /**
             * @description HTTP 상태 코드
             * @example 201
             */
            status: number;
            /**
             * @description 응답 메시지
             * @example success
             */
            message: string;
            /** @description 응답 데이터 */
            data: components["schemas"]["TaskCreateResponseData"];
        };
        ServiceApiResponse: {
            /**
             * @description 성공, 실패 여부 (success, error)
             * @example success
             */
            status: number;
            /**
             * @description 응답 메시지
             * @example success
             */
            message: string;
            /**
             * @description 결과 데이터 (있으면 데이터 출력, 없으면 null)
             * @example null
             */
            data: Record<string, never>;
        };
        TaskUpdateRequest: {
            /** @description 할일 이름 */
            name: string;
        };
        ScheduleItemResponse: {
            /**
             * @description 스케줄 ID
             * @example 1
             */
            scheduleId: number;
            /**
             * @description 할 일 ID
             * @example 1
             */
            taskId: number;
            /**
             * @description 할 일 이름
             * @example 프로젝트 회의
             */
            taskName: string;
            /**
             * @description 시작 시간
             * @example 09:00:00
             */
            startTime: string;
            /**
             * @description 종료 시간
             * @example 10:00:00
             */
            endTime: string;
            /**
             * @description 대상 날짜
             * @example 2026-01-18
             */
            targetDate: string;
            /**
             * @description 완료 여부
             * @example false
             */
            isCompleted: boolean;
        };
        ScheduleListResponse: {
            /** @description 스케줄 목록 */
            schedules: components["schemas"]["ScheduleItemResponse"][];
        };
        ScheduleCreateRequest: {
            /** @description 할 일 ID */
            taskId: number;
            /**
             * @description 할 일 이름
             * @example 프로젝트 회의
             */
            name?: string;
            /**
             * @description 스케줄 시작 시간
             * @example 08:00:00
             */
            startTime: string;
            /**
             * @description 스케줄 끝낼 시간
             * @example 18:00:00
             */
            endTime: string;
            /**
             * @description 스케줄 대상 날짜
             * @example 2026-01-08
             */
            targetDate: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    TaskController_findAll: {
        parameters: {
            query: {
                /** @description 조회 날짜 (YYYY-MM-DD) */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 할 일 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
        };
    };
    TaskController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description 할 일 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreateResponse"];
                };
            };
        };
    };
    TaskController_getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 할 일 상세 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceApiResponse"];
                };
            };
        };
    };
    TaskController_updateContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdateRequest"];
            };
        };
        responses: {
            /** @description 할 일 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 할 일 삭제 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 할 일 완료 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskController_cancelComplete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 할 일 완료 취소 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ScheduleController_findAll: {
        parameters: {
            query: {
                /** @description 조회 날짜 (YYYY-MM-DD) */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 스케줄 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleListResponse"];
                };
            };
        };
    };
    ScheduleController_createSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleCreateRequest"];
            };
        };
        responses: {
            /** @description 스케줄 등록 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceApiResponse"];
                };
            };
        };
    };
    ScheduleController_getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 할 일 상세 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceApiResponse"];
                };
            };
        };
    };
    ScheduleController_updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleCreateRequest"];
            };
        };
        responses: {
            /** @description 스케줄 수정 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceApiResponse"];
                };
            };
        };
    };
    ScheduleController_moveToTodoList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 스케줄 삭제 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ScheduleController_completeSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 스케줄 완료 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ScheduleController_cancelComplete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 스케줄 완료 취소 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ScheduleController_moveToScheduleList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 스케줄 할일 목록으로 이동 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
